# Numpy Basics <hr style="border:2.5px solid #126782"></hr>

Data Analyst: David Lauden R. Santero <br>
Department: Electrical Engineering

In [ ]:
# imports and packages
import numpy as np
from scipy import stats

# Measure of Central Tendency

In [3]:
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [5]:
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [7]:
median_fruits = np.median(fruits)
median_fruits


np.float64(120.0)

In [11]:
mode_fruits = stats.mode(fruits)
mode_fruits

ModeResult(mode=np.int64(60), count=np.int64(1))

In [12]:
jaguar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [14]:
jaguar_mean = np.mean(jaguar)
jaguar_mean

np.float64(9.399999999999999)

In [15]:
median_jaguar = np.median(jaguar)
median_jaguar

np.float64(9.8)

In [17]:
mode_jaguar = stats.mode(jaguar)
mode_jaguar

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [18]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [19]:
panther_mean = np.mean(panther)
panther_mean

np.float64(10.75)

In [21]:
median_panther = np.median(panther)
median_panther

np.float64(9.55)

In [22]:
mode_panther = stats.mode(panther)
mode_panther

ModeResult(mode=np.float64(9.1), count=np.int64(3))