# Numpy Basics <hr style="border:2.5px solid #126782"></hr>

Data Analyst: David Lauden R. Santero <br>
Department: Electrical Engineering

In [23]:
# imports and packages
import numpy as np
from scipy import stats

# 1D Array

In [33]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

# 2D Array

In [35]:
# 2-dimensional array
my_array = np.array([[1,2,3],[4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
my_array =  my_array.T 

In [39]:
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [42]:
# add by row
np.sum(my_array, axis=0)

array([ 6, 15])

In [43]:
# by column
np.sum(my_array, axis=1)


array([5, 7, 9])

# Measure of Central Tendency

In [24]:
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [25]:
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [26]:
median_fruits = np.median(fruits)
median_fruits


np.float64(120.0)

In [27]:
mode_fruits = stats.mode(fruits)
mode_fruits

ModeResult(mode=np.int64(60), count=np.int64(1))

# Jaguar vs Panther


 ## Jaguar

In [32]:
jaguar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [29]:
jaguar_mean = np.mean(jaguar)
jaguar_mean

np.float64(9.399999999999999)

In [30]:
median_jaguar = np.median(jaguar)
median_jaguar

np.float64(9.8)

In [31]:
mode_jaguar = stats.mode(jaguar)
mode_jaguar

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [44]:
max_jaguar = np.max(jaguar)
min_jaguar = np.min(jaguar)

range_jaguar = max_jaguar - min_jaguar
range_jaguar

np.float64(8.0)

In [46]:
q1_jaguar = np.percentile(jaguar,25)
q1_jaguar

np.float64(9.4)

In [50]:
q2_jaguar = np.percentile(jaguar,50)
q2_jaguar



np.float64(9.8)

In [51]:
q3_jaguar = np.percentile(jaguar,75)
q3_jaguar

np.float64(10.45)

In [52]:
iqr_jaguar = q3_jaguar - q1_jaguar
iqr_jaguar

np.float64(1.049999999999999)

In [53]:
# sample variance 
var_jaguar = np.var(jaguar,ddof=1)
var_jaguar

np.float64(4.86)

In [54]:
# sample standard deviation
std_jaguar = np.std(jaguar,ddof=1)
std_jaguar

np.float64(2.2045407685048604)

## Panther

In [18]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [19]:
panther_mean = np.mean(panther)
panther_mean

np.float64(10.75)

In [21]:
median_panther = np.median(panther)
median_panther

np.float64(9.55)

In [22]:
mode_panther = stats.mode(panther)
mode_panther

ModeResult(mode=np.float64(9.1), count=np.int64(3))

In [55]:
max_panther = np.max(panther)
min_panther = np.min(panther)

range_panther = max_panther - min_panther
range_panther


np.float64(10.9)

In [56]:
q1_panther = np.percentile(panther,25)
q1_panther

np.float64(9.125)

In [57]:
q2_panther = np.percentile(panther,50)
q2_panther

np.float64(9.55)

In [58]:
q3_panther = np.percentile(panther,75)
q3_panther

np.float64(10.625)

In [59]:

iqr_panther = q3_panther - q1_panther
iqr_panther

np.float64(1.5)

In [60]:
# sample variance 
var_panther = np.var(panther,ddof=1)
var_panther

np.float64(11.082777777777777)

In [61]:
# sample standard deviation
std_panther = np.std(panther,ddof=1)
std_panther

np.float64(3.3290806204983645)